export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import NavBar from "../components/NavBar"

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
