export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <nav>
          <h1>NavBar</h1>
          <ul>
            <li>Home</li>
            <li>About</li>
            </ul>
        </nav>
        
        {children}</body>
    </html>
  )
}
